### ISSUE TITLE
Clarify how this is different than package:pub_semver

### ISSUE THREAD

**Issue by kevmoo** [convergedtarkus/semver_parser#33]
https://pub.dartlang.org/packages/pub_semver

Would be good for folks to understand which to use...

**Comment by convergedtarkus** [comment]
Excellent point and honestly, I had not seen that package before you mentioned it.

Browsing over the package readme briefly I notice that the pub_semver package intentionally differs from the exact semver 2.0 spec (which has been my guide so far). For example, it factors in the build metadata for determining precedence where semver 2.0 would tell you to ignore this information completely (https://semver.org/#spec-item-10). This makes sense as I assume pub get and similar uses pub_semver for resolving versions.

I can add some information in my README file about the pub_semver package and the differences between the two.  I'll also add that I intended this as a hobby project so consumers of this should take it with a grain of salt. I don't think I have the resources to complete against the whole dart team :)

Thanks for bringing this to my attention and if you feel like a more aggressive strategy is needed to differentiate this from the official dart team package then I'd be happy to discuss that with you.

**Comment by convergedtarkus** [comment]
Addressing in https://github.com/convergedtarkus/semver_parser/pull/38

**Comment by convergedtarkus** [comment]
Addressed in https://github.com/convergedtarkus/semver_parser/pull/38
